# Statistika Deskriptif

Nama : Siti Ulun Nuha Karimah

NIM : 200411100127

Kelas : Penambangan Data A

# 1. Topik Data

Pengelompokkan jenis bunga Iris berdasarkan panjang dan lebar kelopak serta daun kelopak.

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# 1. Membaca data dari url dataset online

untuk membaca dataset kita bisa mengunduh dataset dari internet kemudian mengupload dataset tersebut ke dalam repository github. Setelah itu kita menyalin link raw dataset yang ada dalam repo untuk dibaca dengan cara dibawah ini.

In [4]:
url = "https://raw.githubusercontent.com/SitiUlunNuhaKarimah127/datamining/main/IRIS.csv"
dataset = pd.read_csv(url)

In [5]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [6]:
dataset

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

# 2. Membuat statistik dari data setiap atribut yang bertype numerik

Dalam tugas ini, kita akan melakukan percobaan perhitungan statistic pada data panjang kelopak bunga (sepal length). Cara memanggil data yang ingin dihitung yakni dataset['kelompok_data']

In [7]:
panjang_kelopak = dataset['sepal_length']

# 2.1 Median

Median memiliki pengertian sebagai nilai data tengah. Penyajian data yang dimaksud lebih kepada hasil dari penelitian. Biasanya data tersebut disajikan dalam bentuk tabel, diagram ataupun daftar dan kerap disebut sebagai statistik

Rumus Median :

Rumus Median dengan jumlah data ganjil

$$ Me = \frac{X(n+1)}{2} $$

Rumus Median dengan jumlah data genap:

$$ Me = \frac{X\frac{n}{2}+X(\frac{n}{2}+1)}{2} $$

In [8]:
median = panjang_kelopak.median()
print("Median = ", median)

Median =  5.8

# 2.2 Mean

Mean adalah salah satu ukuran gejala pusat. Mean dapat dikatakan sebagai wakil kumpulan data. Menentukan mean dapat dilakukan dengan cara menjumlahkan seluruh nulai data, kemudian membaginya dengan banyaknya data.

Rumus Mean :


$$ mean = \frac{x1+x2+x3...xn}{n} $$

In [9]:
mean = panjang_kelopak.mean()
print("Mean =", mean)

Mean = 5.843333333333334

# 2.3 Modus

Modus adalah data yang paling sering muncul. Modus merupakan ukuran pemusatan untuk menyatakan fenomena yang paling banyak terjadi. Sekumpulan data yang diperoleh, memungkinkan untuk memiliki nilai modus yang tidak tunggal atau mungkin juga tidak memilikinya.

In [10]:
modus = panjang_kelopak.mode()
print("Modus = ", modus)

Modus =  0    5.0
dtype: float64

# 2.4 Kuartil

Kuartil adalah nilai yang membagi data yang berurutan menjadi empat bagian yang sama banyak. Karena data terbagi menjadi empat bagian yang sama, artinya terdapat tiga nilai kuartil, yaitu kuartil bawah(Q1), kuartil tengah (Q2), dan kuartil atas (Q3).

In [11]:
kuartil = panjang_kelopak.quantile()
print("Kuartil = ", kuartil)

Kuartil =  5.8

# 3. Mendeskripsikan kemiringan / skwened dari data setiap variabel

Kemiringan atau kecondongan(skewness) adalah tingkat ketidaksimetrisan atau kejauhan simetri dari sebuah distribusi. Skewness diartikan sebagai kemiringan distribusi data

In [16]:
skewn = panjang_kelopak.skew()
print("Skewn = ", skewn)

Skewn =  0.3149109566369728